name: test2ambw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/googlelogo1.png
    - assets/images/applelogo1.png
    - lib/googlelogo1.png

fonts:
  - family: Lexend
    fonts:
      - asset: assets/fonts/Lexend/Lexend-Light.ttf
        weight: 300
      - asset: assets/fonts/Lexend/Lexend-Regular.ttf
        weight: 500
      - asset: assets/fonts/Lexend/Lexend-Bold.ttf
        weight: 700
        # style: italic
        # weight: 700