name: test2ambw
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  firebase_auth: ^5.1.0
  firebase_core: ^3.1.0
  flutter:
    sdk: flutter
  hexcolor: ^3.0.1
  supabase_flutter: ^2.0.0
  awesome_bottom_bar: any
  font_awesome_flutter: ^10.7.0
  cupertino_icons: ^1.0.6
  google_fonts: ^6.2.1
  intl: "^0.19.0"
  panara_dialogs: ^0.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/googlelogo1.png
    - assets/images/applelogo1.png
    - lib/googlelogo1.png
  fonts:
    - family: Lexend
      fonts:
        - asset: assets/fonts/Lexend/Lexend-Regular.ttf
        - asset: assets/fonts/Lexend/Lexend-Bold.ttf
          weight: 700
