name: test2ambw
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

assets:
  - lib/assets/images/googlelogo1.png

fonts:
  - family: Lexend
    fonts:
      - asset: lib/assets/fonts/Lexend/Lexend-Light.ttf
      - asset: lib/assets/fonts/Lexend/Lexend-Regular.ttf
      - asset: lib/assets/fonts/Lexend/Lexend-Bold.ttf
        # style: italic
        # weight: 700